# Distribución en el muestreo

## Introducción

Estamos interesados en modelizar un fenómeno que presenta un aspecto aleatorio. Para plantear y contestar preguntas sobre probabilidades de sucesos asociados, buscamos disponer de un modelo para la distribución de los valores de la variable de interés. Iremos construyendo nuestro conocimiento sobre esta distribución al recopilar una muestra de valores, que iremos recogiendo al repetir un experimento.


### Ejemplos {.unnumbered}
- Dispongo de una moneda para tirar a cara o cruz, pero quiero asegurarme de que no está trucada. Para contestar a esta pregunta, planteo el modelo siguiente: si la variable $X$ recoge el resultado de experimento que consiste en tirar una vez la moneda, puede tomar los valores $c$ (Cara) o $+$ (Cruz) con las probabilidades: $\mathbb{P}[X=c]=p$ y $\mathbb{P}[X=+]=1-p.$ La cantidad $p$ es por lo tanto la probabilidad de que salga cara, y es un parámetro de nuestro modelo. En el caso en que confiamos en que la moneda no está trucada, el parámetro $p$ tomará el valor $1/2$. Para sacar información sobre $p$ y comprobar en particular que la moneda no está trucada, repetiremos un cierto número de veces el experimento.
- Para las próximas elecciones generales, queremos determinar la proporción de gente que tiene intención de ir a votar, es decir queremos estimar la tasa de participación. El censo electoral para España tiene unos 35 millones de personas. Es claramente imposible entrevistar a todas las personas del censo, pero puedo realizar una encuesta para conseguir una muestras de respuestas. Planteamos por lo tanto un modelo simple correspondiente al experimento de escoger al azar a una persona censada: si $X$ es la respuesta a la pregunta "Tiene intención de ir a votar?", puede tomar dos valores 1 ó 0 que codifican las respuestas "Sí" o "No" respectivamente. Llamamos $p$ la tasa de intención de voto, es decir que $\mathbb{P}(X = 1) = p$. Quieremos estimar $p$, y lo haremos repetiendo el experimento de escoger una persona al azar en el censo y preguntarle si tiene intención de ir a votar.
- El índice de audiencias manda en la programación de televisión. Pero ¿cómo saben cuántos espectadores vieron un partido dado o un programa determinado? Claramente, no preguntan a todos los potenciales espectadores. En realidad, una encuesta se realiza de manera automática y continua: una empresa especializada llamada Kantar media, [enlace a su página web](https://www.kantar.com/es), ha escogido al azar unos 6000 hogares  que representan unas 20000 personas de entre un total de más de 40 000 000 espectadores potenciales. En cada uno de estos hogares, instala un aparato llamado ``audímetro'' que registra cuál es el programa que se está viendo en cada momento.
- Quiero conocer la concentración de un determinado producto en una solución. Pienso que un modelo razonable para la distribución de los valores proporcionados por mi aparato de medición sea una distribución normal con media $\mu$ y desviación típica $\sigma$ desconocidas. El centro de esta distribución, es decir $\mu$, será por lo tanto lo más representativo de la concentración que intento determinar.  Para estimar $\mu$, repetiré la medición varias veces. 

Pero surge una pregunta evidente:

**Pregunta** ¿Cómo sabemos que nuestra estimación es fiable? ¿Por qué limitándose a unas 20000 personas, se puede extropolar el resultado con confianza a una población de 40 millones? Además está claro que el resultado que obtengo depende de la muestra particular que haya escogido, si hubiera escogido otra muestra, habría obtenido otro resultado. Este hecho se llama la variabilidad muestral.

Para contestar a esta pregunta debo procurar estudiar la variabilidad muestral, es decir conocer la distribución de los valores que toma una cantidad calculada a partir de una muestra concreta, como la proporción por ejemplo, respecto a todas las muestras que podría extraer. Si esta distribución presenta poca dispersión, tendré bastante confianza en que el proceso de estimación es poco sensible a la muestra concreta escogida, puesto que la probabilidad de que otra muestra haya arrojado un valor muy distinto será pequeña.

::: {.callout-note appearance="simple"}
## Inferir
Inferir sobre un parámetro presente en el modelo de distribución de una variable consiste precisamente en sacar información sobre su valor a partir de una muestra de valores de la variable. 

Toda la teoría desarrollada acerca de los sondeos, del control de calidad, del diseño de experimentos, y en realidad, de toda la teoría estadistica se basa de manera esencial en el estudio de la variabilidad muestral de cantidades calculadas a partir de una muestra.
:::

## Muestra aleatoria
Como primer paso en el estudio de la distribución en el muestreo, formalizamos el concepto de muestra aleatoria simple como la variable multidimensional asociada a la repetición de un experimento simple.

::: {#def-mas}
Sea una distribución $f$. Consideramos $n$ variables aleatorias independientes $X_1, X_2, \ldots, X_n$, que tengan cada una la misma distribución $f$. La variable aleatoria multidimensional $(X_1, X_2, \ldots, X_n)$ es una muestra aleatoria simple de $f$.
:::

Decimos que las variables $X_1, X_2, \ldots, X_n$ son independientes e identícamente distribuidas, lo que se abrevia como i.i.d. 
\end{definition}

*Nota:* Por la propiedad de independencia, si $f$ es una función de densidad y $(X_1, X_2, \ldots, X_n)$ es una muestra aleatoria simple de $f$, la función de densidad conjunta de la muestra es el producto de las marginales: 
$$f_{X_1, X_2, \ldots, X_n}(x_1, x_2, \ldots, x_n) = f(x_1)\cdot f(x_2)\cdot \cdots \cdot f(x_n).$$

La situación de modelización más habitual donde consideraremos una muestra aleatoria simple corresponde a la repetición $n$ veces  de manera independiente de un experimento simple al que está asociado una variable $X$ con distribución $f$. Si llamamos $X_1, X_2, \ldots, X_n$ a las variables que recogen los valores de $X$ obtenidos en las $n$ repeticiones, $(X_1, X_2, \ldots, X_n)$ es una muestra aleatoria simple de $f$.

Es el caso del ejemplo descrito en la sección anterior que consiste en tirar $n$ veces una moneda. Si $X_1, X_2, \ldots, X_n$ denotan los valores obtenidos (+ ó c),  $(X_1, X_2, \ldots, X_n)$ es una muestra aleatoria simple de $f$, la distribución de $X$ definida como $\mathbb{P}[X=c]=p$ y $\mathbb{P}[X=+]=1-p.$

En cambio, si consideramos el ejemplo de una encuesta para estimar la tasa de participación, la población de la que se escoge la muestra es finita (unos 35 000 000), y se trata de una extracción sin reemplazo. La probabilidad de que la persona escogida conteste “Sí" va cambiando a medida que vamos entrevistando a gente y depende de las respuestas previas de los encuestados. Por lo tanto, las variables $X_1, X_2, \ldots, X_n$ no son i.i.d. y el vector asociado no forma una muestra aleatoria simple. 

::: {.callout-tip collapse="true"}
### Para saber más 
Si $N_S$ es el número de personas en el censo que tienen intención de ir a votar, y $N$ es el tamaño del censo. Suponiendo que $x_1, x_2, \ldots, x_n$ toman valores 0 ó 1, con la  convención de que $x_i = 1$ si el entrevistado número $i$ declara que tiene intención de ir a votar. Tenemos que 
$$\mathbb{P}(X_i = 1) = \frac {N_S - \sum_{1\leq j< i}x_j} {N - (i - 1)}.$$
:::

## Suma de las variables de una muestra.

Muchas de las cantidades relevantes asociadas a una muestra implican la suma de las variables, empezaremos por lo tanto por estudiar qué podemos decir sobre la distribución muestral de la suma de las variables de una muestra, es decir la distribución de los valores que puede tomar respecto a todas las muestras que se podrían extraer.

::: {#prp-distmas}
Si $(X_1, X_2, \ldots, X_n)$ es una muestra aleatoria simple de $f$, consideramos su suma $S_n = \sum_{i = 1, \ldots, n} X_i$, se cumple:

- Si $\mu_f$ es la esperanza de la distribución $f$, 
  $$\mathbb{E}(S_n)= n\cdot \mu_f.$$
- Si $\sigma_f^2$ es la varianza de la distribución $f$, 
  $$Var(S_n)= n\cdot \sigma_f^2.$$
- Si $\varphi_f$ denota la función característica de $f$, es decir $\forall t$, $\varphi_f(t)= \mathbb{E}[e^{itX}]$ donde $X$ es una variable con distribución $f$,
$$ \varphi_{S_n}(t)=\mathbb{E}[e^{itS_n}]=\left(\varphi_f(t)\right)^n.$$ {#eq-caracteristica-suma}
:::
