project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Fundamentos de inferencia"
  author: "Mathieu Kessler"
  date: "12/23/2022"
  chapters:
    - index.qmd
    - 01-distribucion_en_el_muestreo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



